### PR TITLE
Fix backslash

### PR DESCRIPTION
**Pull request by ciis0**
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/replacements/#field-path-format
image

https://github.com/kubernetes-sigs/cli-experimental/blob/1d7033281bd9f39f9ac9a92cf4b432ae8cdd0896/site/content/en/references/kustomize/kustomization/replacements/_index.md#field-path-format
image

fixed
https://github.com/kubernetes-sigs/cli-experimental/blob/042257d5ef18a72767cd927a61b65cead9bde6fb/site/content/en/references/kustomize/kustomization/replacements/_index.md#field-path-format
image

### CODE REVIEW

**Comment by KnVerey** [comment]
/lgtm
/approve

Please sign the CLA so this can be merged. 😄

**Comment by ciis0** [comment]
Hi,

EasyCLA says

> The Corporate CLA option is not enabled for this project.

image

Who's the Admin in this case?

**Comment by ciis0** [comment]
Ah, was an issue on my side, sorry!

**Comment by KnVerey** [comment]
Since the CLA still isn't signed, I'm going to merge https://github.com/kubernetes-sigs/cli-experimental/pull/263 instead. Please sign it so we can get your next contribution merged. 😄

**Comment by ciis0** [comment]
yes, no problem. :)

**Pull request closed without merging**
