### PR TITLE
Scaffold command structure

### PR DESCRIPTION
**Pull request by pwittrock**
- Setup wire
  - Kubernetes Clientset dependencies and flags
- Create `apply` and `apply status` commands
- Go Modules
- CONTRIBUTING.md

### CODE REVIEW

**Comment by seans3** [comment]
Just so we start off on the right foot; should we also include unit test files?

**Comment by pwittrock** [comment]
@seans3 I am on vacation and won't have time to add them.  Can you make sure that any contributions while I am away adhere to this form and structure?

**Pull request merged**
