### PR TITLE
replacements documentation for escaping '.'

### PR DESCRIPTION
**Pull request by natasha41575**
Add documentation to replacements page for how to escape the '.' in fieldpaths.

Fix https://github.com/kubernetes-sigs/kustomize/issues/4103

/cc @KnVerey

### CODE REVIEW

**Comment by KnVerey** [comment]
New docs look good, but don't we need to regenerate the HTML before merging?

**Comment by natasha41575** [comment]
@KnVerey I ran "hugo" and committed the result, but I noticed it created a new top-level directory called "public". Do you know if I'm supposed to commit that?

**Comment by KnVerey** [comment]
No, you need to run `hugo` from inside the `site/` directory. That should update the `docs/` directory instead of creating "public".

**Comment by natasha41575** [comment]
> No, you need to run hugo from inside the site/ directory. That should update the docs/ directory instead of creating "public".

Cool, thanks! Done and committed

**Pull request merged**
