### PR TITLE
Update components.md

### PR DESCRIPTION
**Pull request by piyushpgupta**
The current url is not valid : https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1802-kustomize-components.md
changing it to : https://github.com/kubernetes/enhancements/blob/master/keps/sig-cli/1802-kustomize-components/README.md

### CODE REVIEW

**Comment by piyushpgupta** [comment]
I signed it

**Comment by piyushpgupta** [comment]
I signed it

**Comment by EppO** [comment]
/lgtm

Thanks for your PR

**Pull request closed without merging**
