### PR TITLE
fix plugins link

### PR DESCRIPTION
**Pull request by HosamAlmoghraby**

### CODE REVIEW

**Comment by HosamAlmoghraby** [comment]
CLA has been signed

**Comment by SyamSundarKirubakaran** [comment]
@HosamAlmoghraby I think it has to be `../../../guides/extending_kustomize/builtins`

**Comment by HosamAlmoghraby** [comment]
> @HosamAlmoghraby I think it has to be `../../../guides/extending_kustomize/builtins`

yes true, I will fix it.
Thank you

**Comment by HosamAlmoghraby** [comment]
> @HosamAlmoghraby I think it has to be `../../../guides/extending_kustomize/builtins`

the relative path is fixed now.

**Review by SyamSundarKirubakaran — APPROVED** [review]
/lgtm

**Pull request merged**
