### PR TITLE
update kustomize docs for patches and openapi

### PR DESCRIPTION
**Pull request by natasha41575**

### CODE REVIEW

**Comment by natasha41575** [comment]
@SyamSundarKirubakaran the CI check appears unrelated to my change (it's failing many for open PRs, not just this one). What's going on there? Is it still possible to merge this PR?

**Comment by SyamSundarKirubakaran** [comment]
@natasha41575 seems like we are using a linter - https://github.com/alecthomas/gometalinter in the CI process which got deprecated. so go get on pre-scripts are failing.

@pwittrock can you suggest.

**Comment by pwittrock** [comment]
@KnVerey

**Comment by KnVerey** [comment]
It looks like we need to switch this repo over to golangci-lint, and that that's actually partway done already. The repo has both a `travis.yml` (correct) and a `travis.yaml` (probably ignored?), where the former installs the deprecated linter and the latter would install the new one. The actual linter script appears to use the new one, though it also attempts to install the old one again. There's an open issue here: https://github.com/kubernetes-sigs/cli-experimental/issues/120

**Comment by natasha41575** [comment]
@KnVerey is anyone working on the issue?

**Review by monopole — APPROVED** [review]
/lgtm

**Pull request merged**
