### PR TITLE
Add github.com/verb/kubectl-debug to plugins

### PR DESCRIPTION
**Pull request by verb**
This creates a directory for experimental plugins and imports https://github.com/verb/kubectl-debug for consideration for inclusion in kubectl itself (https://features.k8s.io/1204).

As discussed in a recent sig-cli meeting, `kubectl debug` closely resembles `kubectl exec` and we should consider adding it into kubectl proper. Until this is decided I'd like to make this functionality available as a plugin to facilitate user feedback. Since we will refer to it from https://kubernetes.io I'd like for it to live in an official project repo, and cli-experimental seems like a good place while it's being discussed with sig-cli.

### CODE REVIEW

**Comment by verb** [comment]
After thinking about it a bit more, I think this is the wrong approach. This should be a separate experimental repo while under consideration by sig-cli. Eventually, one of three things will happen:

1. sig-cli will adopt this functionality into kubectl and the plugin code will necessarily be rewritten into kubectl, making this code redundant.
2. sig-cli will decline to adopt this functionality in kubectl but it should remain a plugin. Regardless of whether this plugin continues to existing in kubernetes-sigs, it should migrate to a standalone repo.
3. Ephemeral containers fails to graduate from alpha and this code is deleted. It's probably easier in this case to just archive the repo.

While we're considering it, I'd like the plugin to be available so we can gather feedback. To integrate with krew I need to be able to make binary releases, which is harder when this is part of cli-experimental. (I'm not sure if I will have permission to make binary releases to a kubernetes-sigs repo, but if not it's still easier for me to maintain a fork with binary releases if this is a standalone repo.)

@seans3 @soltysh @pwittrock Would sig-cli be willing to sponsor a kubernetes-sigs repo for "cli-debug" while this is under consideration? I think this fits well with the [goals for the kubernetes-sigs org](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#sig-repositories).

**Comment by soltysh** [comment]
> @seans3 @soltysh @pwittrock Would sig-cli be willing to sponsor a kubernetes-sigs repo for "cli-debug" while this is under consideration? I think this fits well with the [goals for the kubernetes-sigs org](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#sig-repositories).

I'd suggest creating a kubectl plugin under your private repo but one that will be included in krew's index until sig-cli decides the further steps.

**Comment by verb** [comment]
> I'd suggest creating a kubectl plugin under your private repo but one that will be included in krew's index until sig-cli decides the further steps.

@soltysh This is underway in kubernetes-sigs/krew-index#248, but there was pushback from kubernetes/website approvers to referencing private repos from official documentation (https://github.com/kubernetes/website/pull/15994#discussion_r321965047)

Right now the documentation on http://kubernetes.io about how to use this feature is unacceptably difficult to follow. It's important that we provide something easier sooner rather than later. Maybe referencing a plugin in the krew-index would be good enough.

@kbhawkey @simplytunde @ahmetb  Is it acceptable for https://kubernetes.io to reference krew plugins if they're backed by a private repo?

**Comment by ahmetb** [comment]
> Is it acceptable for [kubernetes.io](https://kubernetes.io) to reference krew plugins if they're backed by a private repo?

In general, the docs are for stuff that are officially maintained. IIRC we even pushed vendor-specific docs out of kubernetes.io. Similarly, I think we would need a repo in one of k8s orgs (with proper code approvals etc) to endorse something in the docs. 

For example, we still have not mentioned krew in the documentation for kubectl plugins yet, but there's an open PR about it,

**Comment by verb** [comment]
At the last sig-cli meeting we agreed to focus on adding a debug command to kubectl proper which would contain this (and other) functionality rather than making an experimental plugin.

I'll close this issue and follow up with sig-docs about possible ways we could document the feature in the interim.

**Pull request closed without merging**
